NodeOUs:
        Enable: true
        ClientOUIdentifier:
            Certificate: cacerts/0-0-0-0-7052.pem
            OrganizationalUnitIdentifier: client
        PeerOUIdentifier:
            Certificate: cacerts/0-0-0-0-7052.pem
            OrganizationalUnitIdentifier: peer
        AdminOUIdentifier:
            Certificate: cacerts/0-0-0-0-7052.pem
            OrganizationalUnitIdentifier: admin
        OrdererOUIdentifier:
            Certificate: cacerts/0-0-0-0-7052.pem
            OrganizationalUnitIdentifier: orderer
